#!/usr/bin/env python3
"""Optional, file-only Caddy exporter. Never starts Caddy or changes listeners."""
from __future__ import annotations

import argparse
import hashlib
import importlib
import ipaddress
import json
import os
from pathlib import Path
import re
import sys
import tempfile

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "providers"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import now_iso, write_json
from webui_transport import caddy_directory
from runtime_state import data_directory


def read_object(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path.name} must contain a JSON object")
    return value


def port_number(value: object, name: str, *, allow_zero: bool = False) -> int:
    text = str(value).strip()
    if not re.fullmatch(r"[0-9]+", text):
        raise ValueError(f"{name} must be an integer")
    number = int(text)
    if not (0 if allow_zero else 1) <= number <= 65535:
        raise ValueError(f"{name} is outside the valid port range")
    return number


def host_name(value: object) -> str:
    """Accept literal addresses/DNS only, never Caddyfile syntax or placeholders."""
    if not isinstance(value, str) or not value:
        raise ValueError("Caddy hosts/backend must be nonempty hostnames or IP addresses")
    if value != value.strip():
        raise ValueError("Caddy hosts/backend cannot contain whitespace")
    if not re.fullmatch(r"[A-Za-z0-9_.:\[\]-]+", value):
        raise ValueError("Caddy hosts/backend contain unsupported characters")
    try:
        address = ipaddress.ip_address(value.strip("[]"))
        return f"[{address}]" if address.version == 6 else str(address)
    except ValueError:
        pass
    if len(value) > 253 or any(not re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9_-]{0,61}[A-Za-z0-9])?", label)
                               for label in value.rstrip(".").split(".")):
        raise ValueError(f"Invalid Caddy hostname: {value!r}")
    return value.rstrip(".")


def allocate(ports: list[int], start: int, steps: int, previous: dict | None) -> dict[str, int]:
    """Persist only port slots. Missing services keep their slots; new ones append."""
    assigned: dict[str, int] = {}
    if previous is not None:
        if previous.get("start") != start or previous.get("steps") != steps:
            raise ValueError("Caddy port settings changed; explicitly move CADDY/ports.json aside to start a new mapping")
        raw = previous.get("ports")
        if not isinstance(raw, dict):
            raise ValueError("Invalid CADDY/ports.json port mapping")
        for key, value in raw.items():
            internal = port_number(key, "backend port")
            public = port_number(value, "frontend port")
            if public < start or (public - start) % steps or public in assigned.values():
                raise ValueError("Invalid or duplicate Caddy frontend allocation")
            if str(internal) in assigned:
                raise ValueError("Duplicate Caddy backend allocation")
            assigned[str(internal)] = public
    next_port = max(assigned.values(), default=start - steps) + steps
    for port in sorted(set(ports)):
        if str(port) in assigned:
            continue
        if next_port > 65535:
            raise ValueError("Caddy frontend port range exhausted")
        assigned[str(port)] = next_port
        next_port += steps
    return assigned


def render(services: list[dict], assignments: dict[str, int], backend: str, hosts: list[str],
           tls_server_name: str = "") -> str:
    lines = ["# Generated by Citadel's caddy export extension. Do not edit.",
             "# HTTPS frontends; upstream protocols come from the current scan.", ""]
    for service in sorted(services, key=lambda row: assignments[str(row["port"])]):
        port = service["port"]
        public = assignments[str(port)]
        sites = ", ".join(f"https://{host}:{public}" for host in hosts)
        lines += [f"# backend {port} -> HTTPS {public}", f"{sites} {{",
                  f"\treverse_proxy {service['scheme']}://{backend}:{port} {{",
                  "\t\theader_up X-Real-IP {remote_host}"]
        if service["scheme"] == "https" and tls_server_name:
            lines += ["\t\ttransport http {", f"\t\t\ttls_server_name {tls_server_name}", "\t\t}"]
        lines += ["\t}", "}", ""]
    return "\n".join(lines).rstrip() + "\n"


def write_text(path: Path, content: str) -> None:
    """Atomic directory-bind-mount-friendly replacement, with no unchanged rewrite."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix=".Caddyfile.", dir=path.parent)
    temporary = Path(name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.chmod(0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def export(root: Path, provider_dir: Path, start_raw: str, steps_raw: str,
           services_file: Path | None = None) -> dict:
    payload = {"provider_id": "caddy", "label": "Caddyfile", "kind": "export",
               "considered": False, "available": False, "generated_at": now_iso(),
               "services": {}, "artifacts": [], "mappings_count": 0, "errors": []}
    try:
        start_text = start_raw.strip()
        start = port_number("0" if start_text.lower() in ("", "blank") else start_text,
                            "CADDYFILE_START", allow_zero=True)
        if not start:
            # Disabling never deletes an operator's mounted file, allocation, or route.
            return payload
        payload["considered"] = True
        steps_text = steps_raw.strip()
        remember = steps_text.lower() not in ("", "blank")
        steps = port_number(steps_text if remember else "1", "CADDYFILE_STEPS")
        config_path = data_directory(root) / "caddy-config.json"
        config = read_object(config_path if config_path.exists() else provider_dir / "config.json.example")
        backend = host_name(config.get("backend", "127.0.0.1"))
        tls_server_name = host_name(config["tls_server_name"]) if config.get("tls_server_name") else ""
        raw_hosts = config.get("hosts", ["localhost"])
        if not isinstance(raw_hosts, list) or not raw_hosts:
            raise ValueError("Caddy hosts must be a nonempty list")
        hosts = list(dict.fromkeys(host_name(host) for host in raw_hosts))
        scanned = read_object(services_file or data_directory(root) / "services.json").get("http_services")
        if not isinstance(scanned, list):
            raise ValueError("services.json must contain an http_services list")
        services = []
        seen = set()
        directory = caddy_directory(root)
        destination = directory / "Caddyfile"
        # A subsequent host scan sees our own HTTPS frontends too. Never export
        # those back into a second, endlessly growing set of frontend ports.
        own_ports = set()
        if destination.is_file():
            own_ports = {int(port) for port in re.findall(
                r"^# backend [0-9]+ -> HTTPS ([0-9]+)$", destination.read_text(), re.M)}
        for row in scanned:
            if not isinstance(row, dict):
                raise ValueError("Invalid scanned service")
            port = port_number(row.get("port"), "backend port")
            if port in own_ports:
                continue
            if row.get("scheme") not in ("http", "https") or port in seen:
                raise ValueError("Scanned services must have unique ports and HTTP/HTTPS protocols")
            seen.add(port)
            services.append({"port": port, "scheme": row["scheme"]})
        allocation_file = directory / "ports.json"
        previous = read_object(allocation_file) if remember and allocation_file.exists() else None
        assigned = allocate(list(seen), start, steps, previous)
        content = render(services, assigned, backend, hosts, tls_server_name)
        # Reserve slots first; a failed file write must not silently reuse a slot later.
        allocation = {"start": start, "steps": steps, "ports": assigned}
        if remember and allocation != previous:
            write_json(str(allocation_file), allocation)
        write_text(destination, content)
        if not remember:
            # Only our allocation ledger; never delete the mounted directory.
            allocation_file.unlink(missing_ok=True)
        payload.update(available=True, generated_file=str(destination), mappings_count=len(services),
                       artifacts=[{"path": "CITADEL_DATA/CADDY/Caddyfile", "sha256": hashlib.sha256(content.encode()).hexdigest()}])
    except (OSError, ValueError, TypeError) as exc:
        payload["errors"].append(str(exc))
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("provider-dir", "services-file", "routes-out"):
        parser.add_argument(f"--{name}", required=True)
    for name in ("cache-dir", "config-ini", "tailscale-file"):
        parser.add_argument(f"--{name}")
    args = parser.parse_args()
    root = Path(args.provider_dir).resolve().parents[2]
    sys.path.insert(0, str(root))
    header = importlib.import_module("python_header")
    payload = export(root, Path(args.provider_dir), header.get("CADDYFILE_START", ""),
                     header.get("CADDYFILE_STEPS", ""), Path(args.services_file))
    write_json(args.routes_out, payload)
    for error in payload["errors"]:
        print(error, file=sys.stderr)
    return 1 if payload["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
